export const TEXT = {
  app: {
    name: 'druzi',
    tagline: 'друзі = friends',
  },
  nav: {
    feed: 'Feed',
    friends: 'Friends',
    profile: 'Profile',
  },
  login: {
    title: 'Welcome Back',
    registerTitle: 'Join Your Friends',
    usernameLabel: 'Username',
    passwordLabel: 'Password',
    displayNameLabel: 'Display Name',
    inviteCodeLabel: 'Invite Code',
    birthdayLabel: 'Birthday (optional)',
    submit: 'Enter',
    register: 'Create Account',
    loading: 'Loading...',
    switchToLogin: 'Already have an account?',
    switchToRegister: "Don't have an account?",
  },
  feed: {
    title: "Today's Moments",
    empty: 'No posts today yet.',
    emptyHint: 'Be the first to share a moment!',
    newPost: '+ New Post',
  },
  post: {
    placeholder: "What's happening?",
    addMedia: '+ Media',
    locationPlaceholder: '📍 Location',
    linkPlaceholder: '🔗 Link',
    submit: 'Post',
    delete: 'Delete',
    confirm: 'Confirm',
    cancel: 'Cancel',
  },
  profile: {
    edit: 'Edit Profile',
    invite: 'Invite a Friend',
    generateInvite: 'Generate Invite Code',
    inviteHint: 'Code expires in 7 days',
    archive: 'Archive',
    noPostsYet: 'No posts yet',
  },
  friends: {
    title: 'Friends',
    empty: 'No friends yet!',
    emptyHint: 'Invite your friends to join druzi',
  },
};
