export const TEXT = {
  app: {
    name: 'druzi',
    tagline: 'друзі = friends',
  },
  nav: {
    feed: 'Feed',
    profile: 'Profile',
  },
  login: {
    title: 'Welcome Back',
    registerTitle: 'Join Your Friends',
    usernameLabel: 'Username',
    passwordLabel: 'Password',
    displayNameLabel: 'Display Name',
    inviteCodeLabel: 'Invite Code',
    birthdayLabel: 'Birthday (optional)',
    submit: 'Enter',
    register: 'Create Account',
    loading: 'Loading...',
    switchToLogin: 'Already have an account?',
    switchToRegister: "Don't have an account?",
  },
  feed: {
    title: "Today's Moments",
    empty: 'No posts today yet.',
    emptyHint: 'Be the first to share a moment!',
    newPost: '+ New Post',
  },
  post: {
    placeholder: "What's happening?",
    addMedia: '+ Media',
    locationPlaceholder: '@ Location',
    linkPlaceholder: '~> Link',
    submit: 'Post',
    delete: 'Delete',
    confirm: 'Confirm',
    cancel: 'Cancel',
  },
  profile: {
    edit: 'Edit Profile',
    invite: 'Invite a Friend',
    generateInvite: 'Generate Invite Code',
    inviteHint: 'Code expires in 7 days',
    archive: 'Archive',
    noPostsYet: 'No posts yet',
  },
  friends: {
    title: 'Friends',
    empty: 'No friends yet!',
    emptyHint: 'Invite your friends to join druzi',
  },
  camera: {
    subtitle: 'Capture a moment',
    photo: 'Photo',
    video: 'Video',
    start: 'Start Camera',
    capture: '[ SNAP ]',
    stop: '[ STOP ]',
    retake: 'Retake',
    use: 'Use This',
    capturingSecond: 'Getting selfie...',
    switchCamera: '(~)',
    front: 'Front',
    back: 'Back',
    recording: 'REC',
    permissionDenied: 'Camera permission denied',
    noCamera: 'No camera found',
  },
  upload: {
    title: 'Upload',
    subtitle: 'Share a file',
    loading: 'Uploading...',
    submit: 'Upload',
    success: 'Upload successful!',
    error: 'Upload failed',
    selected: 'Selected:',
    dropText: 'Drop file here',
    dropHint: 'or click to browse',
  },
  notifications: {
    title: 'Notifications',
    subtitle: 'stay in the loop (◕‿◕)',
    unsupported: 'Notifications are not supported in this browser.',
    denied: 'Notifications blocked. Enable them in your browser settings.',
    enableButton: 'Enable Notifications',
    disableButton: 'Disable Notifications',
    dailyReminder: {
      label: 'Daily Reminder',
      description: 'Get nudged once a day to share a moment',
      nextAt: 'Next reminder at',
    },
    friendPosts: {
      label: 'Friend Posts',
      description: 'Know when your friends share something',
    },
    testButton: '[TEST] Send Now',
    loading: '...',
  },
  hilfe: {
    title: 'About',
    items: [
      'druzi is a private space for friends',
      'Share moments, react with kaomoji',
      'Built with (◠‿◠)',
    ],
  },
};
